from __future__ import annotations

import json
import os
import shutil
from pathlib import Path
from typing import Any

from PIL import Image

from .atlas import get_cell, load_package, save_webp, sha256_file
from .audit import pair_metrics
from .model import (
    ATLAS_HEIGHT,
    ATLAS_WIDTH,
    CELL_HEIGHT,
    CELL_WIDTH,
    OPTIONAL_CELLS,
    ROW_SPECS,
    __version__,
)


def _distance(first: Image.Image, second: Image.Image) -> float:
    metrics = pair_metrics(first, second)
    return (
        metrics["mean_pixel_delta"] * 0.45
        + metrics["luminance_delta"] * 0.25
        + min(metrics["centroid_shift_px"] / 40, 1.0) * 0.20
        + metrics["area_delta_ratio"] * 0.10
    )


def choose_medoid(frames: list[Image.Image]) -> int:
    if not frames:
        raise ValueError("Cannot choose a medoid from zero frames")
    if len(frames) == 1:
        return 0
    totals = []
    for candidate in frames:
        totals.append(sum(_distance(candidate, other) for other in frames))
    return min(range(len(frames)), key=lambda index: (totals[index], index))


def compile_reduced_motion(
    package_dir: str | Path,
    output_dir: str | Path,
    *,
    force: bool = False,
) -> dict[str, Any]:
    package, image = load_package(package_dir)
    destination = Path(output_dir).expanduser().resolve()
    if destination == package.root:
        raise ValueError("Output directory must not replace the source package")
    forbidden = {Path(destination.anchor).resolve(), Path.home().resolve(), Path.cwd().resolve()}
    if destination in forbidden:
        raise ValueError("Refusing to use a broad filesystem location as output")
    if destination.exists():
        if not force:
            raise FileExistsError(f"Output already exists: {destination}")
        if not destination.is_dir():
            raise ValueError(f"Output is not a directory: {destination}")
        marker = destination / "petease-provenance.json"
        if any(destination.iterdir()) and not marker.is_file():
            raise ValueError(
                "Refusing to replace a non-empty directory not previously generated by PetEase"
            )
        shutil.rmtree(destination)
    destination.mkdir(parents=True)

    compiled = Image.new("RGBA", (ATLAS_WIDTH, ATLAS_HEIGHT), (0, 0, 0, 0))
    selections: list[dict[str, Any]] = []
    for spec in ROW_SPECS:
        frames = [get_cell(image, spec.index, column) for column in range(spec.frames)]
        if spec.index >= 9:
            for column, frame in enumerate(frames):
                compiled.paste(frame, (column * CELL_WIDTH, spec.index * CELL_HEIGHT))
            selections.append(
                {
                    "row": spec.index,
                    "state": spec.state,
                    "strategy": "preserve-direction-cells",
                    "selected_frame": None,
                }
            )
            continue

        selected = 0 if spec.state == "idle" else choose_medoid(frames)
        still = frames[selected]
        for column in range(spec.frames):
            compiled.paste(still, (column * CELL_WIDTH, spec.index * CELL_HEIGHT))
        selections.append(
            {
                "row": spec.index,
                "state": spec.state,
                "strategy": "repeat-state-medoid",
                "selected_frame": selected,
            }
        )

    for row, column in sorted(OPTIONAL_CELLS):
        optional = get_cell(image, row, column)
        compiled.paste(optional, (column * CELL_WIDTH, row * CELL_HEIGHT))

    output_sheet = destination / "spritesheet.webp"
    save_webp(compiled, output_sheet)

    manifest = dict(package.manifest)
    manifest["id"] = f"{manifest['id']}-reduced-motion"
    manifest["displayName"] = f"{manifest['displayName']} (Reduced Motion)"
    manifest["description"] = (
        f"{manifest['description'].rstrip()} Reduced-motion edition compiled by PetEase."
    )
    manifest["spritesheetPath"] = output_sheet.name
    (destination / "pet.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    for optional_name in ("FAN_ART_NOTICE.md", "ASSET_LICENSE.md", "NOTICE.md"):
        source = package.root / optional_name
        if source.is_file():
            shutil.copy2(source, destination / optional_name)

    provenance = {
        "schema_version": 1,
        "compiler": {"name": "PetEase", "version": __version__},
        "source": {
            "id": package.manifest["id"],
            "spritesheet_sha256": package.image_sha256,
        },
        "output": {
            "id": manifest["id"],
            "spritesheet_sha256": sha256_file(output_sheet),
        },
        "source_date_epoch": int(os.environ.get("SOURCE_DATE_EPOCH", "1767225600")),
        "strategy": (
            "Repeat one deterministic medoid pose per animated state; preserve all "
            "sixteen static look-direction cells."
        ),
        "selections": selections,
    }
    (destination / "petease-provenance.json").write_text(
        json.dumps(provenance, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    return provenance
